### ISSUE TITLE
Double free in test-queue.cpp line 150-151

### ISSUE THREAD

**Issue by xeniarose** [arthurarmani/software-dev-steven-arthur-public#8]
Currently the strings on those lines will alias to the same String pointer (because peek returns the head of the queue without removing it and pop returns the same head and removes it).

Both peek and pop will point to one of s or s2 as well, which means that the delete call will also delete s and then s2 which will result in further queue pops being invalid (unless we are misunderstanding the spec). The solution is to remove both of these delete statements.

**Comment by sbhornjr** [comment]
So, the other people who are using our spec (@Danijj89) wanted us to delete popped items because they were using copies of pushed strings in their queue. This is also how we implemented our queue, and all of our other data structures. So that the queue has ownership over its stored values and only its stored values. So, when we delete popped elements in the tests, we are not deleting s or s2, we are deleting clones of them.

This is a design choice that you did not have to make, though, so I can remove the deletes and you can use that commit's hash while the other guys use the old commits hash. Just tell me exactly what lines you need fixed (is line 150-151 the only spot?)

**Comment by xeniarose** [comment]
I guess I'm confused about this because the common object interface from the person who did the common object/string interfaces doesn't contain any way to perform a clone of arbitrary objects - so at least for ObjectQueue the queue cannot really copy items to add and thus it cannot have ownership. And considering that it seems a little weird for its subclass StringQueue to break this implicit contract and take ownership of the strings anyway.

Anyway, just 150-151 is all we need removed, yes.

**Comment by sbhornjr** [comment]
Yeah, I was just struggling with that concept myself. We ended up making it so that Objects are always equal to each other - they have no variables, and they have no other distinguishing qualities. We already had all their hashes equal to 0 anyway.

@Danijj89 I am going to change the tests for them, if that breaks things for you just use the commit right before this one in the top level Makefile.

**Comment by sbhornjr** [comment]
Also, in case you were curious, making each object equal to each other didn't work for other reasons so we instead decided to give objects an int ID value to determine equality.

**Comment by xeniarose** [comment]
:+1:
